### ISSUE TITLE
I don't know is steal code

### ISSUE THREAD

**Issue by phoenixatom** [Falcone8/Pyrogram-Userbot#3]
😃

**Comment by Falcone8** [comment]
I only received files to put online I didn't think it was stolen code

**Comment by athphane** [comment]
You could at least give proper credits..

**Comment by Falcone8** [comment]
If you tell me who the original code is I put it between the credits

**Comment by phoenixatom** [comment]
You obviously know who the code is from since you are opening issues in the original repository..

**Comment by Falcone8** [comment]
I swear I didn't know it was stolen code.

**Comment by phoenixatom** [comment]
Hmmmm... https://github.com/athphane/userbot/issues/50

**Comment by Falcone8** [comment]
The guy who downloaded my repository that is the same one who passed me all the files. He noticed the error and told me to point it out to that userbot's dev but I didn't think it was the exact same code.

**Comment by Falcone8** [comment]
I thought he had created it taking inspiration but now I will of course give you all the credits sorry for the unfortunate inconvenience

**Comment by Falcone8** [comment]
I give you the credits immediately

**Comment by Falcone8** [comment]
I apologize again for the mess

**Comment by Falcone8** [comment]
@phoenixatom @athphane I'm so sorry i didn't know it was stolen code
